apiVersion: v1
kind: Service
metadata:
  name: xmaslab2021
  labels:
    name: xmaslab2021
spec:
  selector:
    name: xmaslab2021
  type: LoadBalancer
  ports:
    - port: 80
      name: xmaslab2021
      targetPort: 8080
      protocol: TCP